echo "MIUI EXTREME Debloater: a simple script to increase the battery and speed up your Xiaomi!"
echo "NOTE: If you read FAILURE [not installed for 0], it's because the service isn't already present in your Xiaomi."
echo "Removing all shit..."
adb shell pm uninstall --user 0 com.android.theme.icon.pebble
adb shell pm uninstall --user 0 com.android.theme.icon.vessel
adb shell pm uninstall --user 0 com.android.theme.icon.taperedrect
adb shell pm uninstall --user 0 com.android.theme.icon.teardrop
adb shell pm uninstall --user 0 com.android.theme.icon.squircle
adb shell pm uninstall --user 0 com.android.theme.icon.roundedrect
adb shell pm uninstall --user 0 com.android.theme.color.cinnamon
adb shell pm uninstall --user 0 com.android.theme.color.black
adb shell pm uninstall --user 0 com.android.theme.color.green
adb shell pm uninstall --user 0 com.android.theme.color.ocean
adb shell pm uninstall --user 0 com.android.theme.color.space
adb shell pm uninstall --user 0 com.android.theme.color.orchid
adb shell pm uninstall --user 0 com.android.theme.color.purple
adb shell pm uninstall --user 0 com.android.theme.icon_pack.circular.android
adb shell pm uninstall --user 0 com.android.theme.icon_pack.circular.systemui
adb shell pm uninstall --user 0 com.android.theme.icon_pack.circular.settings
adb shell pm uninstall --user 0 com.android.theme.icon_pack.filled.android
adb shell pm uninstall --user 0 com.android.theme.icon_pack.filled.systemui
adb shell pm uninstall --user 0 com.android.theme.icon_pack.filled.settings
adb shell pm uninstall --user 0 com.android.theme.icon_pack.rounded.android
adb shell pm uninstall --user 0 com.android.theme.icon_pack.rounded.systemui
adb shell pm uninstall --user 0 com.android.theme.icon_pack.rounded.settings
adb shell pm uninstall --user 0 com.android.theme.icon_pack.kai.android
adb shell pm uninstall --user 0 com.android.theme.icon_pack.kai.systemui
adb shell pm uninstall --user 0 com.android.theme.icon_pack.kai.settings
adb shell pm uninstall --user 0 com.android.theme.icon_pack.sam.android
adb shell pm uninstall --user 0 com.android.theme.icon_pack.sam.systemui
adb shell pm uninstall --user 0 com.android.theme.icon_pack.sam.settings
adb shell pm uninstall --user 0 com.android.theme.icon_pack.victor.android
adb shell pm uninstall --user 0 com.android.theme.icon_pack.victor.systemui
adb shell pm uninstall --user 0 com.android.theme.icon_pack.victor.settings
adb shell pm uninstall --user 0 com.android.hotwordenrollment.okgoogle
adb shell pm uninstall --user 0 com.google.android.apps.tachyon
adb shell pm uninstall --user 0 com.mi.android.globalpersonalassistant
adb shell pm uninstall --user 0 com.google.ar.lens
adb shell pm uninstall --user 0 com.mi.globalTrendNews
adb shell pm uninstall --user 0 com.miui.personalassistant
adb shell pm uninstall --user 0 com.google.android.marvin.talkback
adb shell pm uninstall --user 0 com.miui.analytics
adb shell pm uninstall --user 0 com.miui.virtualsim
adb shell pm uninstall --user 0 com.mi.android.globalminusscreen
adb shell pm uninstall --user 0 com.google.ar.lens
adb shell pm uninstall --user 0 com.google.android.videos
adb shell pm uninstall --user 0 com.google.android.music
adb shell pm uninstall --user 0 com.miui.powerkeeper
adb shell pm uninstall --user 0 com.xiaomi.calendar
adb shell pm uninstall --user 0 ru.yandex.searchplugin
adb shell pm uninstall --user 0 com.android.emergency
adb shell pm uninstall --user 0 com.android.cellbroadcastreceiver
adb shell pm uninstall --user 0 com.mi.health
adb shell pm uninstall --user 0 com.miui.player
adb shell pm uninstall --user 0 com.miui.enbbs
adb shell pm uninstall --user 0 com.duokan.phone.remotecontroller
adb shell pm uninstall --user 0 com.duokan.phone.remotecontroller.peel.plugin
adb shell pm uninstall --user 0 com.xiaomi.midrop
adb shell pm uninstall --user 0 com.google.android.talk
adb shell pm uninstall --user 0 com.miui.backup
adb shell pm uninstall --user 0 com.xiaomi.mirecycle
adb shell pm uninstall --user 0 com.miui.antispam
adb shell pm uninstall --user 0 com.android.browser
adb shell pm uninstall --user 0 com.facemoji.lite.xiaomi
adb shell pm uninstall --user 0 com.miui.userguide
adb shell pm uninstall --user 0 com.android.calendar
adb shell pm uninstall --user 0 com.miui.cleanmaster
adb shell pm uninstall --user 0 com.bsp.catchlog
adb shell pm uninstall --user 0 com.miui.compass
adb shell pm uninstall --user 0 com.google.android.apps.wellbeing
adb shell pm uninstall --user 0 com.android.providers.downloads.ui
adb shell pm uninstall --user 0 com.facebook.appmanager
adb shell pm uninstall --user 0 com.facebook.services
adb shell pm uninstall --user 0 com.facebook.system
adb shell pm uninstall --user 0 com.miui.newhome
adb shell pm uninstall --user 0 com.miui.powerkeeper
adb shell pm uninstall --user 0 com.miui.calculator
adb shell pm uninstall --user 0 com.miui.deskclock
adb shell pm uninstall --user 0 com.miui.newhome
adb shell pm uninstall --user 0 com.miui.bugreport
adb shell pm uninstall --user 0 com.miui.freeform
adb shell pm uninstall --user 0 com.miui.phrase
adb shell pm uninstall --user 0 com.xiaomi.glgm
adb shell pm uninstall --user 0 com.xiaomi.mipicks
adb shell pm uninstall --user 0 com.google.android.googlequicksearchbox
adb shell pm uninstall --user 0 com.google.android.apps.googleassistant
adb shell pm uninstall --user 0 com.google.android.calendar
adb shell pm uninstall --user 0 com.android.chrome
adb shell pm uninstall --user 0 com.google.android.apps.maps
adb shell pm uninstall --user 0 com.google.android.apps.subscriptions.red
adb shell pm uninstall --user 0 com.miui.hybrid.accessory
adb shell pm uninstall --user 0 com.xiaomi.joyose
adb shell pm uninstall --user 0 com.android.email
adb shell pm uninstall --user 0 com.miui.msa.global
adb shell pm uninstall --user 0 com.google.android.feedback
adb shell pm uninstall --user 0 com.miui.cloudbackup
adb shell pm uninstall --user 0 com.miui.cloudservice
adb shell pm uninstall --user 0 com.sohu.inputmethod.sogou.xiaomi
adb shell pm uninstall --user 0 com.miui.cloudservice.sysbase
adb shell pm uninstall --user 0 com.miui.micloudsync
adb shell pm uninstall --user 0 com.xiaomi.payment
adb shell pm uninstall --user 0 com.android.midrive
adb shell pm uninstall --user 0 com.netflix.partner.activation
adb shell pm uninstall --user 0 com.netflix.mediaclient
adb shell pm uninstall --user 0 com.opera.app.news
adb shell pm uninstall --user 0 com.opera.branding
adb shell pm uninstall --user 0 com.opera.branding.news
adb shell pm uninstall --user 0 com.opera.preinstall
adb shell pm uninstall --user 0 com.miui.systemAdSolution
adb shell pm uninstall --user 0 com.miui.voceassist
adb shell pm uninstall --user 0 com.mipay.wallet
adb shell pm uninstall --user 0 com.xiaomi.miplay_client
adb shell pm uninstall --user 0 com.miui.nextpay
adb shell pm uninstall --user 0 com.miui.miservice
adb shell pm uninstall --user 0 com.xiaomi.midrop
adb shell pm uninstall --user 0 com.miui.translation.kingsoft
adb shell pm uninstall --user 0 com.miui.translation.xmcloud
adb shell pm uninstall --user 0 com.miui.translation.youdao
adb shell pm uninstall --user 0 com.miui.translationservice
adb shell pm uninstall --user 0 com.mipay.wallet.in
adb shell pm uninstall --user 0 com.mipay.wallet.id
adb shell pm uninstall --user 0 com.miui.mishare.connectivity
adb shell pm uninstall --user 0 com.xiaomi.mi_connect_service
adb shell pm uninstall --user 0 com.xiaomi.mipicks
adb shell pm uninstall --user 0 com.xiaomi.miplay_client
adb shell pm uninstall --user 0 com.mi.webkit.core
adb shell pm uninstall --user 0 com.miui.notes
adb shell pm uninstall --user 0 com.miui.global.packageinstaller
adb shell pm uninstall --user 0 com.android.providers.partnerbookmarks
adb shell pm uninstall --user 0 com.miui.daemon
adb shell pm uninstall --user 0 com.miui.hybrid
adb shell pm uninstall --user 0 com.miui.touchassistant
adb shell pm uninstall --user 0 com.miui.smsextra
adb shell pm uninstall --user 0 com.xiaomi.scanner
adb shell pm uninstall --user 0 com.miui.translation.kingsoft
adb shell pm uninstall --user 0 com.miui.translation.xmcloud
adb shell pm uninstall --user 0 com.miui.miservice
adb shell pm uninstall --user 0 com.tencent.soter.soterserver
adb shell pm uninstall --user 0 com.milink.service
adb shell pm uninstall --user 0 com.miui.vsimcore
adb shell pm uninstall --user 0 com.miui.wmsvc
adb shell pm uninstall --user 0 com.miui.weather2
adb shell pm uninstall --user 0 com.google.ar.core
adb shell pm uninstall --user 0 com.xiaomi.simactivate.service
adb shell pm uninstall --user 0 com.xiaomi.xmsf
adb shell pm uninstall --user 0 com.xiaomi.xmsfkeeper
adb shell pm uninstall --user 0 com.miui.yellowpage
adb shell pm uninstall --user 0 com.miui.fashiongallery
echo "Enjoy! Now the phone is clean :)"
